// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKjk_V7cU041qwnCmubJbQZ556oUEVHII',
    appId: '1:1011915138729:web:91b67dcd9c8dc74d562bb8',
    messagingSenderId: '1011915138729',
    projectId: 'capstone-c4d77',
    authDomain: 'capstone-c4d77.firebaseapp.com',
    storageBucket: 'capstone-c4d77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLQM-2nHpFngqgL7grLVs7NpjOvh5efc',
    appId: '1:1011915138729:android:2a248dd403041036562bb8',
    messagingSenderId: '1011915138729',
    projectId: 'capstone-c4d77',
    storageBucket: 'capstone-c4d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCzvi4zyTx2EP7BmMHyAYMbOowIW4CEI',
    appId: '1:1011915138729:ios:8d26be11845937dc562bb8',
    messagingSenderId: '1011915138729',
    projectId: 'capstone-c4d77',
    storageBucket: 'capstone-c4d77.appspot.com',
    iosClientId: '1011915138729-rf6mfju2810d8aa2milt8k5hrlm108pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petlose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaCzvi4zyTx2EP7BmMHyAYMbOowIW4CEI',
    appId: '1:1011915138729:ios:8d26be11845937dc562bb8',
    messagingSenderId: '1011915138729',
    projectId: 'capstone-c4d77',
    storageBucket: 'capstone-c4d77.appspot.com',
    iosClientId: '1011915138729-rf6mfju2810d8aa2milt8k5hrlm108pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petlose',
  );
}
